---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
before_install: gem install bundler -v 2.0.1
